package com.backend.devConnectBackend.service;

import com.backend.devConnectBackend.dto.LoginRequest;
import com.backend.devConnectBackend.dto.LoginResult;
import com.backend.devConnectBackend.dto.RegisterRequest;
import com.backend.devConnectBackend.model.User;
import com.backend.devConnectBackend.repository.UserRepository;
import com.backend.devConnectBackend.security.JwtService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class AuthService {

    private final UserRepository repo;
    private final JwtService jwt;
    private final BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

    public AuthService(UserRepository repo, JwtService jwt) {
        this.repo = repo;
        this.jwt = jwt;
    }

    public void register(RegisterRequest request) {
        if (repo.findByEmail(request.email()).isPresent()) {
            throw new com.backend.devConnectBackend.exception.UserAlreadyExistsException("User already exists!");
        }

        String hashed = encoder.encode(request.password());
        User user = new User(
                null, // id will be generated by MongoDB
                request.name(),
                request.email(),
                hashed,
                request.role(),
                request.skills());
        repo.save(user);
    }

    /**
     * Authenticate user with email and password.
     * Uses Null Object pattern - returns result object instead of throwing
     * exceptions.
     * 
     * @param req Login request with email and password
     * @return LoginResult - one of: Success, UserNotFound, or InvalidPassword
     */
    public LoginResult login(LoginRequest req) {
        Optional<User> userOpt = repo.findByEmail(req.email());

        if (userOpt.isEmpty()) {
            return new LoginResult.UserNotFound();
        }

        User user = userOpt.get();

        if (!encoder.matches(req.password(), user.getPassword())) {
            return new LoginResult.InvalidPassword();
        }

        String token = jwt.generateToken(user.getEmail(), user.getRole());
        return new LoginResult.Success(token);
    }
}
